# Generated by Django 4.1.5 on 2023-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
